# @see https://wiki.openstreetmap.org/wiki/User:Roland.olbricht/Data_Items_as_Relations

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wdt: <https://wiki.openstreetmap.org/prop/direct/>

SELECT 
  ?item
  ?desc
  ?p10
  ?label__ar
  ?label__en
  ?desc__ar
  ?desc__en
  # (GROUP_CONCAT(?label ; SEPARATOR = "|||") AS ?label_X)
  # (GROUP_CONCAT(?desc ; SEPARATOR = "|||") AS ?desc_X)
WHERE {
  ?item a wikibase:Property;
      # skos:prefLabel ?label;
      # schema:description ?desc;
  .
  OPTIONAL { ?item wdt:P10 ?p10 . }
  OPTIONAL { ?item skos:prefLabel ?label filter (lang(?label) = "en"). }
  OPTIONAL { ?item schema:description ?desc filter (lang(?desc) = "en"). }
  OPTIONAL { ?item skos:prefLabel ?label__ar filter (lang(?label__ar) = "ar"). }
  OPTIONAL { ?item skos:prefLabel ?label__en filter (lang(?label__en) = "en"). }
  OPTIONAL { ?item schema:description ?desc__ar filter (lang(?desc__ar) = "ar"). }
  OPTIONAL { ?item schema:description ?desc__en filter (lang(?desc__en) = "en"). }
}
ORDER BY DESC(?item)
# to strip the en from "languate tag"en: https://stackoverflow.com/questions/35889050/get-string-without-the-language-tag